name: puzzlify
description: "A Flutter widget that turns any image into an interactive puzzle game."
version: 0.0.1

homepage: https://github.com/amirsalarrabaniha/puzzlify
repository: https://github.com/amirsalarrabaniha/puzzlify
issue_tracker: https://github.com/amirsalarrabaniha/puzzlify/issues

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Example: Adding assets if you want to include images/GIFs for README
  assets:
    - assets/img1.png
    - assets/img2.png
